version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: compliance_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/compliance_app
      JWT_SECRET: your_jwt_secret_key
      EMAIL_HOST: smtp.example.com
      EMAIL_PORT: 587
      EMAIL_USER: your_email@example.com
      EMAIL_PASS: your_email_password
      EMAIL_FROM: your_email@example.com
      FRONTEND_URL: http://localhost:3000
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    volumes:
      - ./backend/uploads:/app/uploads
    command: sh -c "npx prisma migrate deploy && npm start"

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data: